/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package procesos;

import formato.Agregar;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JPanel;
/**
 *
 * @author felic
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---" }));
        comboProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---" }));
        comboSubproceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---" }));
        conectar cc = new conectar();
        Connection con = cc.conexion();
        PreparedStatement insVenta;
        botonBuscar.setEnabled(false);
        try{
        insVenta = con.prepareStatement("Select * from Areas");
        ResultSet Areas = insVenta.executeQuery();
        while(Areas.next())
        {
            comboArea.addItem(Areas.getString("Nombre"));
        }
           }
        
        catch(Exception e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jpInicio = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbLogin = new javax.swing.JLabel();
        jlbAyuda = new javax.swing.JLabel();
        jpNuevo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpTitulo = new javax.swing.JPanel();
        jlbTitulo = new javax.swing.JLabel();
        comboArea = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        comboProceso = new javax.swing.JComboBox<>();
        etiqueta = new javax.swing.JLabel();
        comboSubproceso = new javax.swing.JComboBox<>();
        botonBuscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtProceso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDueno = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        jlbSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bgPanel.setBackground(java.awt.SystemColor.controlHighlight);
        bgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 29, 80));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("[M-FC]");
        sidePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 190, 30));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 190, 10));

        jpInicio.setBackground(new java.awt.Color(106, 118, 125));
        jpInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpInicioMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_home_32px.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Inicio");

        javax.swing.GroupLayout jpInicioLayout = new javax.swing.GroupLayout(jpInicio);
        jpInicio.setLayout(jpInicioLayout);
        jpInicioLayout.setHorizontalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpInicioLayout.setVerticalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addGroup(jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidePanel.add(jpInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 40));

        jlbLogin.setBackground(new java.awt.Color(106, 118, 125));
        jlbLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_enter_32px.png"))); // NOI18N
        jlbLogin.setToolTipText("Iniciar Sesión");
        jlbLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        jlbLogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbLogin.setOpaque(true);
        jlbLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbLoginMousePressed(evt);
            }
        });
        sidePanel.add(jlbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 50, 50));

        jlbAyuda.setBackground(new java.awt.Color(106, 118, 125));
        jlbAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_help_32px.png"))); // NOI18N
        jlbAyuda.setToolTipText("Iniciar Sesión");
        jlbAyuda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        jlbAyuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jlbAyuda.setOpaque(true);
        jlbAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbAyudaMousePressed(evt);
            }
        });
        sidePanel.add(jlbAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 50, 50));

        jpNuevo.setBackground(new java.awt.Color(106, 118, 125));
        jpNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpNuevoMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_add_32px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Agregar Nuevo");

        javax.swing.GroupLayout jpNuevoLayout = new javax.swing.GroupLayout(jpNuevo);
        jpNuevo.setLayout(jpNuevoLayout);
        jpNuevoLayout.setHorizontalGroup(
            jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpNuevoLayout.setVerticalGroup(
            jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNuevoLayout.createSequentialGroup()
                .addGroup(jpNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        sidePanel.add(jpNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        bgPanel.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 700));

        jpTitulo.setBackground(new java.awt.Color(0, 176, 240));
        jpTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlbTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitulo.setText("Gestor de Procesos");
        jlbTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jpTitulo.add(jlbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 80));

        bgPanel.add(jpTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 930, 100));

        comboArea.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboArea.setForeground(new java.awt.Color(0, 29, 80));
        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboArea.setBorder(null);
        comboArea.setFocusCycleRoot(true);
        comboArea.setName("comboArea"); // NOI18N
        comboArea.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboAreaItemStateChanged(evt);
            }
        });
        comboArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAreaMouseClicked(evt);
            }
        });
        comboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaActionPerformed(evt);
            }
        });
        bgPanel.add(comboArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 201, 760, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Proceso");
        bgPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, -1));

        comboProceso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboProceso.setForeground(new java.awt.Color(0, 29, 80));
        comboProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboProceso.setName("comboProceso"); // NOI18N
        comboProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProcesoActionPerformed(evt);
            }
        });
        bgPanel.add(comboProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 273, 760, 30));

        etiqueta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta.setText("Sub Proceso");
        etiqueta.setVisible(false);
        bgPanel.add(etiqueta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 130, -1));

        comboSubproceso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        comboSubproceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboSubproceso.setName("comboSubproceso"); // NOI18N
        comboSubproceso.setVisible(false);
        comboSubproceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSubprocesoActionPerformed(evt);
            }
        });
        bgPanel.add(comboSubproceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 760, 30));

        botonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        botonBuscar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(0, 29, 80));
        botonBuscar.setText("Buscar");
        botonBuscar.setToolTipText("Buscar Proceso seleccionado");
        botonBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        botonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        botonBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonBuscar.setMaximumSize(new java.awt.Dimension(60, 50));
        botonBuscar.setMinimumSize(new java.awt.Dimension(60, 50));
        botonBuscar.setName("botonBuscar"); // NOI18N
        botonBuscar.setPreferredSize(new java.awt.Dimension(80, 30));
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        bgPanel.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 80, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Área");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bgPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jPanel2.setBackground(new java.awt.Color(228, 228, 228));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Informacion del Proceso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 30, 80))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Proceso:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        txtProceso.setEditable(false);
        txtProceso.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 620, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Sub Proceso:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        txtSub.setEditable(false);
        txtSub.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 620, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Área Dueña:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        txtDueno.setEditable(false);
        txtDueno.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtDueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 620, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Responsable:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txtResponsable.setEditable(false);
        txtResponsable.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtResponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 620, -1));

        bgPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 910, 240));

        jlbSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlbSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-close-window-32.png"))); // NOI18N
        jlbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbSalirMousePressed(evt);
            }
        });
        bgPanel.add(jlbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1142, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAreaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboAreaItemStateChanged

    }//GEN-LAST:event_comboAreaItemStateChanged

    private void comboAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAreaMouseClicked

    }//GEN-LAST:event_comboAreaMouseClicked

    private void comboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaActionPerformed
        comboSubproceso.setVisible(false);
        etiqueta.setVisible(false);
        botonBuscar.setEnabled(false);
        conectar cc = new conectar();
        Connection con = cc.conexion();
        int idArea=0;
        try{
            PreparedStatement getIdArea = con.prepareStatement("Select * from areas where nombre ='"+ comboArea.getSelectedItem().toString()+"'");
            ResultSet getArea = getIdArea.executeQuery();
            while(getArea.next())
            {
                idArea = getArea.getInt("idArea");
            }

            PreparedStatement buscarProcesos = con.prepareStatement("Select * from proceso where idArea ="+ idArea);
            ResultSet nombreProcesos = buscarProcesos.executeQuery();
            comboProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---" }));
            while(nombreProcesos.next())
            {
                comboProceso.addItem(nombreProcesos.getString("Nombre"));
            }
        }
        catch(SQLException e){  System.out.println(e);}

    }//GEN-LAST:event_comboAreaActionPerformed

    private void comboProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProcesoActionPerformed
        conectar cc = new conectar();
        Connection con = cc.conexion();
        int idProceso = 0;
        try{
            if(!"---Seleccionar---".equals(comboProceso.getSelectedItem().toString())){
                PreparedStatement consultarsub = con.prepareStatement("Select * from subproceso where idDocumento =(Select idDocumento from proceso where nombre ='" + comboProceso.getSelectedItem().toString()+"')");
                ResultSet idSub = consultarsub.executeQuery();
                comboSubproceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccionar---" }));
                while (idSub.next())
                {
                    comboSubproceso.addItem(idSub.getString("nombre"));

                }
                if(comboSubproceso.getItemCount()>1)
                {
                    etiqueta.setVisible(true);
                    comboSubproceso.setVisible(true);
                    botonBuscar.setEnabled(false);
                }
                else{
                    comboSubproceso.setVisible(false);
                    etiqueta.setVisible(false);
                    botonBuscar.setEnabled(true);
                }
            }
            else {
                comboSubproceso.setVisible(false);
                etiqueta.setVisible(false);
                botonBuscar.setEnabled(false);
            }

        }

        catch(SQLException e){System.out.println(e);}
    }//GEN-LAST:event_comboProcesoActionPerformed

    private void comboSubprocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSubprocesoActionPerformed
        conectar cc = new conectar();
        Connection con = cc.conexion();
        if(!"---Seleccionar---".equals(comboSubproceso.getSelectedItem().toString()))
        {
            botonBuscar.setEnabled(true);
        }
        else{
            botonBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_comboSubprocesoActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed

        conectar cc = new conectar();
        Connection con = cc.conexion();
        String tabla = null;
        String comboTabla = null;
        try
        {
            if(comboSubproceso.isVisible())
            {
                tabla = "subproceso";
                comboTabla = comboSubproceso.getSelectedItem().toString();
            }
            else {
                tabla = "proceso";
                comboTabla = comboProceso.getSelectedItem().toString();
            }

            PreparedStatement consultarRuta = con.prepareStatement("select ruta from "+tabla+ " where nombre = '" +comboTabla+"'");
            ResultSet Resruta = consultarRuta.executeQuery();
            String ruta= null;
            while(Resruta.next())
            {
                ruta = Resruta.getString("ruta");
            }
            System.out.println(ruta);
            abrirarchivo(ruta);
        }

        catch(SQLException e){System.out.println(e);}

    }//GEN-LAST:event_botonBuscarActionPerformed

    private void jlbSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlbSalirMousePressed

    private void jpNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpNuevoMousePressed
        // TODO add your handling code here:
        setColor(jpNuevo);
        resetColor(jpInicio);
        Agregar addNuevo = new Agregar();
        addNuevo.setVisible(true);
    }//GEN-LAST:event_jpNuevoMousePressed

    private void jlbLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbLoginMousePressed
        // TODO add your handling code here:
        //jlbLogin.setBackground(new Color(180,180,180));
        login ventana = new login();
        ventana.setVisible(true);
        //jlbLogin.setBackground(new Color(106,118,125));
    }//GEN-LAST:event_jlbLoginMousePressed

    private void jlbAyudaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbAyudaMousePressed
        // TODO add your handling code here:
        Ayuda vayuda = new Ayuda();
        vayuda.setVisible(true);
    }//GEN-LAST:event_jlbAyudaMousePressed

    private void jpInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpInicioMousePressed
        // TODO add your handling code here:
        setColor(jpInicio);
        resetColor(jpNuevo);
    }//GEN-LAST:event_jpInicioMousePressed
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(180,180,180));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(106,118,125));
    }
    
    public void abrirarchivo(String archivo){

         try {

                File objetofile = new File (archivo);
                Desktop.getDesktop().open(objetofile);

         }catch (IOException ex) {

                System.out.println(ex);}
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JComboBox<String> comboArea;
    private javax.swing.JComboBox<String> comboProceso;
    private javax.swing.JComboBox<String> comboSubproceso;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbAyuda;
    private javax.swing.JLabel jlbLogin;
    private javax.swing.JLabel jlbSalir;
    private javax.swing.JLabel jlbTitulo;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JPanel jpNuevo;
    private javax.swing.JPanel jpTitulo;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField txtDueno;
    private javax.swing.JTextField txtProceso;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtSub;
    // End of variables declaration//GEN-END:variables
}
