/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formato;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import paneles.CambiaPanel;

/**
 *
 * @author felic
 */
public class Agregar extends javax.swing.JFrame {
    
    int x, y;
    /**
     * Creates new form Agregar
     */
    public Agregar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnGenerales.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new paneles.pnlGenerales());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnMenu = new rsbuttom.RSButtonMetro();
        jlbSalir = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        btnDiagrama = new rsbuttom.RSButtonMetro();
        btnGenerales = new rsbuttom.RSButtonMetro();
        btnFase0 = new rsbuttom.RSButtonMetro();
        btnFase1 = new rsbuttom.RSButtonMetro();
        btnFase34 = new rsbuttom.RSButtonMetro();
        btnWhatif = new rsbuttom.RSButtonMetro();
        btnLecciones = new rsbuttom.RSButtonMetro();
        btnAnexos = new rsbuttom.RSButtonMetro();
        pnlCentro = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1300, 650));

        jPanel1.setMaximumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel3.setBackground(new java.awt.Color(0, 29, 80));

        btnMenu.setForeground(new java.awt.Color(0, 29, 80));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-menu-64.png"))); // NOI18N
        btnMenu.setColorHover(new java.awt.Color(106, 118, 125));
        btnMenu.setColorNormal(new java.awt.Color(0, 29, 80));
        btnMenu.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        jlbSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbSalir.setForeground(new java.awt.Color(255, 255, 255));
        jlbSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-ventana-32.png"))); // NOI18N
        jlbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jlbSalirMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMenu.setBackground(java.awt.SystemColor.controlHighlight);
        pnlMenu.setMaximumSize(new java.awt.Dimension(32767, 200));
        pnlMenu.setPreferredSize(new java.awt.Dimension(200, 200));

        btnDiagrama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnDiagrama.setText("Diagrama");
        btnDiagrama.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDiagrama.setColorHover(new java.awt.Color(106, 118, 125));
        btnDiagrama.setColorNormal(new java.awt.Color(0, 29, 80));
        btnDiagrama.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnDiagrama.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnDiagrama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDiagramaMousePressed(evt);
            }
        });
        btnDiagrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagramaActionPerformed(evt);
            }
        });

        btnGenerales.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnGenerales.setText("Generales");
        btnGenerales.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGenerales.setColorHover(new java.awt.Color(106, 118, 125));
        btnGenerales.setColorNormal(new java.awt.Color(0, 29, 80));
        btnGenerales.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnGenerales.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGenerales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGeneralesMousePressed(evt);
            }
        });
        btnGenerales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneralesActionPerformed(evt);
            }
        });

        btnFase0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnFase0.setText("Fase 0");
        btnFase0.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFase0.setColorHover(new java.awt.Color(106, 118, 125));
        btnFase0.setColorNormal(new java.awt.Color(0, 29, 80));
        btnFase0.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnFase0.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFase0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFase0MousePressed(evt);
            }
        });
        btnFase0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFase0ActionPerformed(evt);
            }
        });

        btnFase1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnFase1.setText("Fase 1");
        btnFase1.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFase1.setColorHover(new java.awt.Color(106, 118, 125));
        btnFase1.setColorNormal(new java.awt.Color(0, 29, 80));
        btnFase1.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnFase1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFase1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFase1MousePressed(evt);
            }
        });
        btnFase1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFase1ActionPerformed(evt);
            }
        });

        btnFase34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnFase34.setText("Fase 3-4");
        btnFase34.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnFase34.setColorHover(new java.awt.Color(106, 118, 125));
        btnFase34.setColorNormal(new java.awt.Color(0, 29, 80));
        btnFase34.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnFase34.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFase34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFase34MousePressed(evt);
            }
        });
        btnFase34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFase34ActionPerformed(evt);
            }
        });

        btnWhatif.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnWhatif.setText("What If");
        btnWhatif.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnWhatif.setColorHover(new java.awt.Color(106, 118, 125));
        btnWhatif.setColorNormal(new java.awt.Color(0, 29, 80));
        btnWhatif.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnWhatif.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnWhatif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnWhatifMousePressed(evt);
            }
        });
        btnWhatif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWhatifActionPerformed(evt);
            }
        });

        btnLecciones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnLecciones.setText("Lecciones Aprendidas");
        btnLecciones.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLecciones.setColorHover(new java.awt.Color(106, 118, 125));
        btnLecciones.setColorNormal(new java.awt.Color(0, 29, 80));
        btnLecciones.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnLecciones.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnLecciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLeccionesMousePressed(evt);
            }
        });
        btnLecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeccionesActionPerformed(evt);
            }
        });

        btnAnexos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 29, 80), 1, true));
        btnAnexos.setText("Anexos");
        btnAnexos.setColorBorde(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAnexos.setColorHover(new java.awt.Color(106, 118, 125));
        btnAnexos.setColorNormal(new java.awt.Color(0, 29, 80));
        btnAnexos.setColorPressed(java.awt.SystemColor.activeCaptionBorder);
        btnAnexos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAnexos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAnexosMousePressed(evt);
            }
        });
        btnAnexos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnexosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLecciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWhatif, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDiagrama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnexos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFase0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFase34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFase1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFase0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFase1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFase34, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnWhatif, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLecciones, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDiagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pnlCentro.setBackground(java.awt.SystemColor.controlHighlight);

        pnlPrincipal.setBackground(java.awt.SystemColor.controlHighlight);
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1057, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        // TODO add your handling code here:
        int position = this.pnlMenu.getX();
        if (position > -1) {
            Animacion.Animacion.mover_izquierda(0, -363, 2, 2, pnlMenu);
        }else{
            Animacion.Animacion.mover_derecha(-363, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnGeneralesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneralesActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlGenerales());
        if (this.btnGenerales.isSelected()) {
            this.btnGenerales.setColorNormal(new Color (118,118,118));
            this.btnGenerales.setColorHover(new Color (118,118,118));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnGeneralesActionPerformed

    private void btnGeneralesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeneralesMousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(true);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnGeneralesMousePressed

    private void btnFase0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFase0ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlFase0());
        if (this.btnFase0.isSelected()) {
            this.btnFase0.setColorNormal(new Color (118,118,118));
            this.btnFase0.setColorHover(new Color (118,118,118));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnFase0ActionPerformed

    private void btnFase0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFase0MousePressed
        // TODO add your handling code here
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(true);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnFase0MousePressed

    private void btnFase1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFase1ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlFase1());
        if (this.btnFase1.isSelected()) {
            this.btnFase1.setColorNormal(new Color (118,118,118));
            this.btnFase1.setColorHover(new Color (118,118,118));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnFase1ActionPerformed

    private void btnFase1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFase1MousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(true);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnFase1MousePressed

    private void btnFase34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFase34ActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlFase34());
        if (this.btnFase34.isSelected()) {
            this.btnFase34.setColorNormal(new Color (118,118,118));
            this.btnFase34.setColorHover(new Color (118,118,118));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
        }

    }//GEN-LAST:event_btnFase34ActionPerformed

    private void btnFase34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFase34MousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(true);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnFase34MousePressed

    private void btnWhatifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWhatifActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlWhatif());
        if (this.btnWhatif.isSelected()) {
            this.btnWhatif.setColorNormal(new Color (118,118,118));
            this.btnWhatif.setColorHover(new Color (118,118,118));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnWhatifActionPerformed

    private void btnWhatifMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWhatifMousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(true);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnWhatifMousePressed

    private void btnLeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeccionesActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlLecciones());
        if (this.btnLecciones.isSelected()) {
            this.btnLecciones.setColorNormal(new Color (118,118,118));
            this.btnLecciones.setColorHover(new Color (118,118,118));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnLeccionesActionPerformed

    private void btnLeccionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLeccionesMousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(true);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnLeccionesMousePressed

    private void btnAnexosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnexosActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlAnexos());
        if (this.btnAnexos.isSelected()) {
            this.btnAnexos.setColorNormal(new Color (118,118,118));
            this.btnAnexos.setColorHover(new Color (118,118,118));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }else{
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnAnexosActionPerformed

    private void btnAnexosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnexosMousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(true);
        this.btnDiagrama.setSelected(false);
    }//GEN-LAST:event_btnAnexosMousePressed

    private void btnDiagramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagramaActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal, new paneles.pnlDiagrama());
        if (this.btnDiagrama.isSelected()) {
            this.btnDiagrama.setColorNormal(new Color (118,118,118));
            this.btnDiagrama.setColorHover(new Color (118,118,118));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
            
            this.btnGenerales.setColorNormal(new Color (0,29,80));
            this.btnGenerales.setColorHover(new Color (106,118,125));
            this.btnGenerales.setColorPressed(new Color (118,118,118));
            
            this.btnFase0.setColorNormal(new Color (0,29,80));
            this.btnFase0.setColorHover(new Color (106,118,125));
            this.btnFase0.setColorPressed(new Color (118,118,118));
            
            this.btnFase1.setColorNormal(new Color (0,29,80));
            this.btnFase1.setColorHover(new Color (106,118,125));
            this.btnFase1.setColorPressed(new Color (118,118,118));
            
            this.btnFase34.setColorNormal(new Color (0,29,80));
            this.btnFase34.setColorHover(new Color (106,118,125));
            this.btnFase34.setColorPressed(new Color (118,118,118));
            
            this.btnWhatif.setColorNormal(new Color (0,29,80));
            this.btnWhatif.setColorHover(new Color (106,118,125));
            this.btnWhatif.setColorPressed(new Color (118,118,118));
            
            this.btnLecciones.setColorNormal(new Color (0,29,80));
            this.btnLecciones.setColorHover(new Color (106,118,125));
            this.btnLecciones.setColorPressed(new Color (118,118,118));
            
            this.btnAnexos.setColorNormal(new Color (0,29,80));
            this.btnAnexos.setColorHover(new Color (106,118,125));
            this.btnAnexos.setColorPressed(new Color (118,118,118));
        }else{
            this.btnDiagrama.setColorNormal(new Color (0,29,80));
            this.btnDiagrama.setColorHover(new Color (106,118,125));
            this.btnDiagrama.setColorPressed(new Color (118,118,118));
        }
    }//GEN-LAST:event_btnDiagramaActionPerformed

    private void btnDiagramaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDiagramaMousePressed
        // TODO add your handling code here:
        this.btnGenerales.setSelected(false);
        this.btnFase0.setSelected(false);
        this.btnFase1.setSelected(false);
        this.btnFase34.setSelected(false);
        this.btnWhatif.setSelected(false);
        this.btnLecciones.setSelected(false);
        this.btnAnexos.setSelected(false);
        this.btnDiagrama.setSelected(true);
    }//GEN-LAST:event_btnDiagramaMousePressed

    private void jlbSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbSalirMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jlbSalirMousePressed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnAnexos;
    private rsbuttom.RSButtonMetro btnDiagrama;
    private rsbuttom.RSButtonMetro btnFase0;
    private rsbuttom.RSButtonMetro btnFase1;
    private rsbuttom.RSButtonMetro btnFase34;
    private rsbuttom.RSButtonMetro btnGenerales;
    private rsbuttom.RSButtonMetro btnLecciones;
    private rsbuttom.RSButtonMetro btnMenu;
    private rsbuttom.RSButtonMetro btnWhatif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlbSalir;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
