/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author felic
 */
public class pnlGenerales extends javax.swing.JPanel {

    /**
     * Creates new form pnlGeneral
     */
    public pnlGenerales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNivel1 = new javax.swing.JLabel();
        txtNivel1 = new javax.swing.JTextField();
        lblNivel2 = new javax.swing.JLabel();
        txtNivel2 = new javax.swing.JTextField();
        lblNivel3 = new javax.swing.JLabel();
        txtNivel3 = new javax.swing.JTextField();
        lblNivel4 = new javax.swing.JLabel();
        txtNivel4 = new javax.swing.JTextField();
        lblNivel41 = new javax.swing.JLabel();
        txtNivel41 = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        lblResponsable = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        lblEstrategias = new javax.swing.JLabel();
        cbx1 = new javax.swing.JCheckBox();
        cbx2 = new javax.swing.JCheckBox();
        cbx3 = new javax.swing.JCheckBox();
        cbx4 = new javax.swing.JCheckBox();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblDocumentacion = new javax.swing.JLabel();
        txtDocumentacion = new javax.swing.JTextField();
        lblActualizacion = new javax.swing.JLabel();
        txtActualizacion = new javax.swing.JTextField();

        setBackground(java.awt.SystemColor.controlHighlight);
        setMaximumSize(new java.awt.Dimension(1057, 621));
        setMinimumSize(new java.awt.Dimension(1057, 621));
        setPreferredSize(new java.awt.Dimension(1057, 621));

        lblNivel1.setBackground(new java.awt.Color(0, 29, 80));
        lblNivel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNivel1.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel1.setText("Nivel 1 Macroproceso:");
        lblNivel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNivel1.setName("lblNivel1"); // NOI18N
        lblNivel1.setOpaque(true);

        txtNivel1.setEditable(false);
        txtNivel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNivel1.setForeground(new java.awt.Color(0, 29, 80));
        txtNivel1.setText("Proceso de Dirección o Soporte");
        txtNivel1.setName("txtNivel1"); // NOI18N

        lblNivel2.setBackground(new java.awt.Color(0, 29, 80));
        lblNivel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNivel2.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel2.setText("Nivel 2 Proceso de Negocio:");
        lblNivel2.setName("lblNivel2"); // NOI18N
        lblNivel2.setOpaque(true);

        txtNivel2.setEditable(false);
        txtNivel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNivel2.setForeground(new java.awt.Color(0, 29, 80));
        txtNivel2.setText("Controlling Producto");
        txtNivel2.setName("txtNivel2"); // NOI18N

        lblNivel3.setBackground(new java.awt.Color(0, 29, 80));
        lblNivel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNivel3.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel3.setText("Nivel 3 Proceso:");
        lblNivel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblNivel3.setName("lblNivel3"); // NOI18N
        lblNivel3.setOpaque(true);

        txtNivel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNivel3.setForeground(new java.awt.Color(0, 29, 80));
        txtNivel3.setText("Nombre Oficial del Proceso");
        txtNivel3.setName("txtNivel3"); // NOI18N

        lblNivel4.setBackground(new java.awt.Color(0, 29, 80));
        lblNivel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNivel4.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel4.setText("Nivel 4 Sub Proceso:");
        lblNivel4.setName("lblNivel4"); // NOI18N
        lblNivel4.setOpaque(true);

        txtNivel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNivel4.setForeground(new java.awt.Color(0, 29, 80));
        txtNivel4.setText("Nombre Oficial del Sub Proceso");
        txtNivel4.setName("txtNivel4"); // NOI18N

        lblNivel41.setBackground(new java.awt.Color(0, 29, 80));
        lblNivel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblNivel41.setForeground(new java.awt.Color(255, 255, 255));
        lblNivel41.setText("Nivel 4.1 Sub Proceso:");
        lblNivel41.setName("lblNivel41"); // NOI18N
        lblNivel41.setOpaque(true);

        txtNivel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNivel41.setForeground(new java.awt.Color(0, 29, 80));
        txtNivel41.setText("Nombre Oficial del Sub Proceso 4.1");
        txtNivel41.setName("txtNivel41"); // NOI18N

        lblArea.setBackground(new java.awt.Color(0, 29, 80));
        lblArea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblArea.setForeground(new java.awt.Color(255, 255, 255));
        lblArea.setText("Área Dueña:");
        lblArea.setName("lblArea"); // NOI18N
        lblArea.setOpaque(true);

        txtArea.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtArea.setForeground(new java.awt.Color(0, 29, 80));
        txtArea.setText("[M-FCC]");
        txtArea.setName("txtArea"); // NOI18N

        lblResponsable.setBackground(new java.awt.Color(0, 29, 80));
        lblResponsable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResponsable.setForeground(new java.awt.Color(255, 255, 255));
        lblResponsable.setText("Responsable (Dueño):");
        lblResponsable.setName("lblResponsable"); // NOI18N
        lblResponsable.setOpaque(true);

        txtResponsable.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtResponsable.setForeground(new java.awt.Color(0, 29, 80));
        txtResponsable.setName("txtResponsable"); // NOI18N

        lblEstrategias.setBackground(new java.awt.Color(0, 29, 80));
        lblEstrategias.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEstrategias.setForeground(new java.awt.Color(255, 255, 255));
        lblEstrategias.setText("Estrategia a la que está alineada:");
        lblEstrategias.setName("lblEstrategias"); // NOI18N
        lblEstrategias.setOpaque(true);

        cbx1.setBackground(new java.awt.Color(255, 255, 255));
        cbx1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbx1.setForeground(new java.awt.Color(0, 29, 80));
        cbx1.setText("1. Petición de un cliente (p.ej Reporte)");
        cbx1.setName("cbx1"); // NOI18N

        cbx2.setBackground(new java.awt.Color(255, 255, 255));
        cbx2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbx2.setForeground(new java.awt.Color(0, 29, 80));
        cbx2.setText("2. KPI (Seguimiento)");
        cbx2.setName("cbx2"); // NOI18N

        cbx3.setBackground(new java.awt.Color(255, 255, 255));
        cbx3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbx3.setForeground(new java.awt.Color(0, 29, 80));
        cbx3.setText("4. TOC");
        cbx3.setName("cbx4"); // NOI18N

        cbx4.setBackground(new java.awt.Color(255, 255, 255));
        cbx4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cbx4.setForeground(new java.awt.Color(0, 29, 80));
        cbx4.setText("3. Layout (inicio de otro proceso)");
        cbx4.setName("cbx3"); // NOI18N

        lblFecha.setBackground(new java.awt.Color(0, 29, 80));
        lblFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha de Documentación:");
        lblFecha.setName("lblFecha"); // NOI18N
        lblFecha.setOpaque(true);

        txtFecha.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 29, 80));
        txtFecha.setName("txtFecha"); // NOI18N

        lblDocumentacion.setBackground(new java.awt.Color(0, 29, 80));
        lblDocumentacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblDocumentacion.setForeground(new java.awt.Color(255, 255, 255));
        lblDocumentacion.setText("Responsable de la Documentación:");
        lblDocumentacion.setName("lblDocumentacion"); // NOI18N
        lblDocumentacion.setOpaque(true);

        txtDocumentacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDocumentacion.setForeground(new java.awt.Color(0, 29, 80));
        txtDocumentacion.setName("txtDocumentacion"); // NOI18N

        lblActualizacion.setBackground(new java.awt.Color(0, 29, 80));
        lblActualizacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblActualizacion.setForeground(new java.awt.Color(255, 255, 255));
        lblActualizacion.setText("Actualización:");
        lblActualizacion.setName("lblActualizacion"); // NOI18N
        lblActualizacion.setOpaque(true);

        txtActualizacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtActualizacion.setForeground(new java.awt.Color(0, 29, 80));
        txtActualizacion.setName("txtActualizacion"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstrategias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNivel4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx3, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbx4, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNivel41, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNivel41, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(219, 219, 219))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtNivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtNivel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblNivel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblNivel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblNivel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNivel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNivel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstrategias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbx1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbx3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtActualizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbx1;
    private javax.swing.JCheckBox cbx2;
    private javax.swing.JCheckBox cbx3;
    private javax.swing.JCheckBox cbx4;
    private javax.swing.JLabel lblActualizacion;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblDocumentacion;
    private javax.swing.JLabel lblEstrategias;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNivel1;
    private javax.swing.JLabel lblNivel2;
    private javax.swing.JLabel lblNivel3;
    private javax.swing.JLabel lblNivel4;
    private javax.swing.JLabel lblNivel41;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JTextField txtActualizacion;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtDocumentacion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNivel1;
    private javax.swing.JTextField txtNivel2;
    private javax.swing.JTextField txtNivel3;
    private javax.swing.JTextField txtNivel4;
    private javax.swing.JTextField txtNivel41;
    private javax.swing.JTextField txtResponsable;
    // End of variables declaration//GEN-END:variables
}
